service: dashboard-pushover-webhook

provider:
  name: aws
  runtime: python3.7
  environment:
    PUSHOVER_USER_KEY: ${env:PUSHOVER_USER_KEY}
    PUSHOVER_APP_KEY: ${env:PUSHOVER_APP_KEY}
    PRIORITY: 0
    SOUND: pushover
    DEVICE: ''

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: post
